export const CHECK_SESSION = 'checkSession'
export const LOGIN = 'login'
export const LOGGED_IN = 'loggedIn'
export const GET_BOARDS = 'getBoards'
export const RECEIVE_BOARDS = 'receiveBoards'
export const GET_PINS = 'getPins'
export const RECEIVE_PINS = 'receivePins'
export const NEXT_IMAGE = 'nextImage'
